In [2]:
import numpy as np
import pandas as pd
from scipy.stats import chi2

In [3]:
# data init
DATA = pd.DataFrame({
        "First group": {
            "Small": 25,
            "Exact": 50,
            "Big": 25
        },
        "Second group": {
            "Small": 52,
            "Exact": 41,
            "Big": 7
        }
    })

n = np.sum(DATA)

DATA

       First group  Second group
Small           25            52
Exact           50            41
Big             25             7

In [4]:
# sample probabilities calculation
group_probabilities = DATA.sum() / n
size_probabilities = DATA.sum(axis=1) / n

random_vector_probabilities = pd.DataFrame(
    np.outer(size_probabilities.values, group_probabilities.values),
    index=size_probabilities.index,
    columns=group_probabilities.index,
)
random_vector_probabilities

       First group  Second group
Small       0.1925        0.1925
Exact       0.2275        0.2275
Big         0.0800        0.0800

In [5]:
delta = np.sum(
    (DATA - random_vector_probabilities * n) ** 2 /
    (random_vector_probabilities * n)
)

(DATA - random_vector_probabilities * n) ** 2 / (random_vector_probabilities * n)

       First group  Second group
Small     4.733766      4.733766
Exact     0.445055      0.445055
Big       5.062500      5.062500

In [ ]:
# p-value calculation
chi2.sf(delta,  df=(2 - 1) * (3 - 1))  # 1 - F(x)

np.float64(3.566569773595299e-05)