In [2]:
import numpy as np
import pandas as pd
from scipy.stats import chi2

In [3]:
# data init
DATA = pd.DataFrame({
    "First group": {
        2: 33,
        3: 43,
        4: 80,
        5: 144
    },
    "Second group": {
        2: 39,
        3: 35,
        4: 72,
        5: 154
    }
})

N = np.sum(DATA)

DATA

   First group  Second group
2           33            39
3           43            35
4           80            72
5          144           154

In [ ]:
# sample probabilities calculation
probabilities = DATA.sum(axis=1) / N
probabilities

2    0.120000
3    0.130000
4    0.253333
5    0.496667
dtype: float64

In [15]:
delta = np.sum(
    (DATA.T - probabilities * 300) ** 2 /
    (probabilities * 300)
)

(DATA.T - probabilities * 300) ** 2 / (probabilities * 300)

                 2         3         4         5
First group   0.25  0.410256  0.210526  0.167785
Second group  0.25  0.410256  0.210526  0.167785

In [ ]:
# p-value calculation
chi2.sf(delta,  df=(4 - 1) * (2 - 1))  # 1 - F(x)

np.float64(0.5565521530460769)